kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

  - name: tests_debian
    image: gitlight/deb-stable-py3
    pull: true
    commands:
      - . /venv/testenv/bin/activate
      - pip3 install -r requirements/tests.txt
      - make test
    branches: master
    when:
      event: [ push, pull_request ]

  #- name: lint
  #  image: gitlight/deb-stable-py3
  #  pull: true
  #  commands:
  #    - 'virtualenv /tmp/.venv'
  #    - '. /tmp/.venv/bin/activate'
  #    - 'pip install -r requirements/tests.txt'
  #    - 'python ./manage.py tests'
  #  branches: master
  #  when:
  #    event: [ push, pull_request ]

  #- name: docs
  #  image: gitlight/deb-stable-py3
  #  pull: true
  #  commands:
  #    - 'virtualenv /tmp/.venv'
  #    - '. /tmp/.venv/bin/activate'
  #    - 'pip install -r requirements/docs.txt'
  #    - 'python ./manage.py docs'
  #  branches: master
  #  when:
  #    event: [ push, pull_request ]

  - name: coverage
    image: gitlight/deb-stable-py3
    pull: true
    commands:
      - . /venv/testenv/bin/activate
      - pip3 install -r requirements/tests.txt
      - make coverage-text
    branches: master
    when:
      event: [ push, pull_request ]
