FROM debian:testing
MAINTAINER Michael Lustfield "mtecknology@debian.net"
RUN apt-get update && apt-get install -y python3 python3-dev python3.7-dev python-pip python3-virtualenv libssl-dev libpq-dev git build-essential libfontconfig1 libfontconfig1-dev python3-venv
RUN python3 -m venv /venv/testenv
