FROM debian:testing
RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-dev python3.7-dev python-pip python3-virtualenv libssl-dev libpq-dev git build-essential libfontconfig1 libfontconfig1-dev python3-venv
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN python3 -m venv /venv/testenv
